# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitsu < Formula
  desc "Switch git user easily"
  homepage "https://github.com/matsuyoshi30/gitsu"
  version "0.2.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/matsuyoshi30/gitsu/releases/download/v0.2.1/gitsu_0.2.1_darwin_x86_64.tar.gz"
    sha256 "72ddfbb339fa4f4617bc7a05310b2cf62051e48b4999230cf52609dc0152d9ce"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/matsuyoshi30/gitsu/releases/download/v0.2.1/gitsu_0.2.1_linux_x86_64.tar.gz"
    sha256 "9ddad6a63d32b91a21c518e413f29b1d92e1a64f57a50595dcb80cdaf3dc8b0b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/matsuyoshi30/gitsu/releases/download/v0.2.1/gitsu_0.2.1_linux_arm64.tar.gz"
    sha256 "c8c7a2c37397509aead395e7659be4c5e10453d1a7c38bfbba01ab9716f653af"
  end

  def install
    bin.install "git-su"
  end
end
