# This file was generated by GoReleaser. DO NOT EDIT.
class Gitsu < Formula
  desc "Switch git user easily"
  homepage "https://github.com/matsuyoshi30/gitsu"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/matsuyoshi30/gitsu/releases/download/v0.1.1/gitsu_0.1.1_darwin_x86_64.tar.gz"
    sha256 "ed56b5647c31e81bb221a92e49fb595672ef21d49c81ff5eae2bbd4c02fc98c7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/matsuyoshi30/gitsu/releases/download/v0.1.1/gitsu_0.1.1_linux_x86_64.tar.gz"
    sha256 "80c9d65fe384dc70b03ca70939781eafd5bbba2aea77678a20778b5490d64788"
  end

  def install
    bin.install "git-su"
  end
end
